# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 16:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('extension', models.FloatField()),
                ('mdt', models.CharField(max_length=100)),
                ('pnoa', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=25830)),
            ],
        ),
    ]
